import re
import string

#contraction list
cList = {
  "ain't": "am not",
  "aren't": "are not",
  "aint": "am not",
  "arent": "are not",
  "can't": "cannot",
  "can't've": "cannot have",
  "'cause": "because",
  "could've": "could have",
  "couldn't": "could not",
  "couldn't've": "could not have",
  "didn't": "did not",
  "doesn't": "does not",
  "don't": "do not",
  "hadn't": "had not",
  "hadn't've": "had not have",
  "hasn't": "has not",
  "haven't": "have not",
  "he'd": "he would",
  "he'd've": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "I'd": "I would",
  "I'd've": "I would have",
  "I'll": "I will",
  "I'll've": "I will have",
  "I'm": "I am",
  "I've": "I have",
  "isn't": "is not",
  "it'd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "let's": "let us",
  "lets": "let us",
  "ma'am": "madam",
  "maam": "madam",
  "mayn't": "may not",
  "might've": "might have",
  "mightn't": "might not",
  "mightn't've": "might not have",
  "must've": "must have",
  "mustn't": "must not",
  "mustn't've": "must not have",
  "needn't": "need not",
  "needn't've": "need not have",
  "o'clock": "of the clock",
  "oughtn't": "ought not",
  "oughtn't've": "ought not have",
  "shan't": "shall not",
  "sha'n't": "shall not",
  "shan't've": "shall not have",
  "she'd": "she would",
  "she'd've": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "she's": "she is",
  "should've": "should have",
  "shouldn't": "should not",
  "shouldn't've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "that'd": "that would",
  "that'd've": "that would have",
  "that's": "that is",
  "there'd": "there had",
  "there'd've": "there would have",
  "there's": "there is",
  "they'd": "they would",
  "they'd've": "they would have",
  "they'll": "they will",
  "they'll've": "they will have",
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd": "we had",
  "we'd've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll": "what will",
  "what'll've": "what will have",
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll": "who will",
  "who'll've": "who will have",
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "won't've": "will not have",
  "would've": "would have",
  "wouldn't": "would not",
  "wouldn't've": "would not have",
  "y'all": "you all",
  "y'alls": "you alls",
  "y'all'd": "you all would",
  "y'all'd've": "you all would have",
  "y'all're": "you all are",
  "y'all've": "you all have",
  "you'd": "you had",
  "you'd've": "you would have",
  "you'll": "you you will",
  "you'll've": "you you will have",
  "you're": "you are",
  "you've": "you have"
}


negation_list = [
  'no',
  'not',
  'never',
  'nobody',
  'none',
  'neither',
  'nothing',
  'nowhere',
  'barely',
  'rarely',
  'seldom',
  'hardly',
  'scarcely',
]


emoticons_str = r"""
    (?:
        [:=;] # Eyes
        [oO\-]? # Nose (optional)
        [D\)\]\(\]\\OpP] # Mouth
    )"""

regex_str = [
    emoticons_str,
    # r'<[^>]+>',  # HTML tags
    # r'(?:@[\w_]+)',  # @-mentions
    r"(?:\#+[\w_]+[\w\'_\-]*[\w_]+)",  # hash-tags
    # r'http[s]?://(?:[a-z]|[0-9]|[$-_@.&amp;+]|[!*\(\),]|(?:%[0-9a-f][0-9a-f]))+',  # URLs
    # r'(?:(?:\d+,?)+(?:\.?\d+)?)',  # numbers
    # r"(?:[a-z][a-z'\-_]+[a-z])",  # words with - and '
    r'(?:[\w_]+)',  # other words
    # r'(?:\S)'  # anything else
]

punctuation = list(set(string.punctuation))
punc_str = ''
for i in punctuation:
  punc_str = punc_str +i


negative_emoji_list = [
ur"\U0001f612",
ur"\U0001f613",
ur"\U0001f614",
ur"\U0001f615",
ur"\U0001f616",
ur"\U0001f61e",
ur"\U0001f61f",
ur"\U0001f620",
ur"\U0001f621",
ur"\U0001f622",
ur"\U0001f623",
ur"\U0001f624",
ur"\U0001f625",
ur"\U0001f626",
ur"\U0001f627",
ur"\U0001f628",
ur"\U0001f629",
ur"\U0001f62b",
ur"\U0001f63e",
ur"\U0001f63f",
]

positive_emoji_list = [
ur"\U0001f600",
ur"\U0001f601",
ur"\U0001f603",
ur"\U0001f604",
ur"\U0001f606",
ur"\U0001f609",
ur"\U0001f60a",
ur"\U0001f60b",
ur"\U0001f60c",
ur"\U0001f60d",
ur"\U0001f60e",
ur"\U0001f60f",
ur"\U0001f617",
ur"\U0001f618",
ur"\U0001f619",
ur"\U0001f61a",
ur"\U0001f62c",
ur"\U0001f638",
ur"\U0001f63a",
ur"\U0001f63b",
ur"\U0001f63c",
ur"\U0001f63d",
]